/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicadental.com.view;

/**
 *
 * @author jank
 */
public class actualizar extends javax.swing.JFrame {

    /**
     * Creates new form actualizar
     */
    public actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        serviciotxt = new javax.swing.JTextField();
        apellidotxt = new javax.swing.JTextField();
        edadtxt = new javax.swing.JTextField();
        cedulatxt = new javax.swing.JTextField();
        codigotxt = new javax.swing.JTextField();
        fechatxt = new javax.swing.JTextField();
        descripciontxt = new javax.swing.JTextField();
        nombretxt = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        preciotxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VER/ACTUALIZAR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("APELLIDO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EDAD:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CEDULA:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CODIGO:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FECHA:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DESCRIPCION:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TIPO SERVICIO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        serviciotxt.setBackground(new java.awt.Color(6, 88, 147));
        serviciotxt.setForeground(new java.awt.Color(255, 255, 255));
        serviciotxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163)));
        jPanel1.add(serviciotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 80, -1));

        apellidotxt.setBackground(new java.awt.Color(6, 88, 147));
        apellidotxt.setForeground(new java.awt.Color(255, 255, 255));
        apellidotxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163)));
        jPanel1.add(apellidotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 80, -1));

        edadtxt.setBackground(new java.awt.Color(6, 88, 147));
        edadtxt.setForeground(new java.awt.Color(255, 255, 255));
        edadtxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163)));
        edadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadtxtActionPerformed(evt);
            }
        });
        jPanel1.add(edadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, -1));

        cedulatxt.setBackground(new java.awt.Color(6, 88, 147));
        cedulatxt.setForeground(new java.awt.Color(255, 255, 255));
        cedulatxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163)));
        jPanel1.add(cedulatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 80, -1));

        codigotxt.setBackground(new java.awt.Color(6, 88, 147));
        codigotxt.setForeground(new java.awt.Color(255, 255, 255));
        codigotxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163)));
        codigotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigotxtActionPerformed(evt);
            }
        });
        jPanel1.add(codigotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 80, -1));

        fechatxt.setBackground(new java.awt.Color(6, 88, 147));
        fechatxt.setForeground(new java.awt.Color(255, 255, 255));
        fechatxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163)));
        jPanel1.add(fechatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 80, -1));

        descripciontxt.setBackground(new java.awt.Color(6, 88, 147));
        descripciontxt.setForeground(new java.awt.Color(255, 255, 255));
        descripciontxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163)));
        jPanel1.add(descripciontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 80, -1));

        nombretxt.setBackground(new java.awt.Color(6, 88, 147));
        nombretxt.setForeground(new java.awt.Color(255, 255, 255));
        nombretxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163)));
        jPanel1.add(nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 80, -1));

        btnActualizar.setBackground(new java.awt.Color(71, 192, 167));
        btnActualizar.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 100, 30));

        btncerrar.setBackground(new java.awt.Color(71, 192, 167));
        btncerrar.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btncerrar.setForeground(new java.awt.Color(255, 255, 255));
        btncerrar.setText("CERRAR");
        btncerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 70, 30));

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PRECIO:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        preciotxt.setBackground(new java.awt.Color(6, 88, 147));
        preciotxt.setForeground(new java.awt.Color(255, 255, 255));
        preciotxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163), new java.awt.Color(251, 228, 163)));
        jPanel1.add(preciotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 80, -1));

        jLabel1.setBackground(new java.awt.Color(6, 88, 147));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadtxtActionPerformed

    private void codigotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigotxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField apellidotxt;
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btncerrar;
    public javax.swing.JTextField cedulatxt;
    public javax.swing.JTextField codigotxt;
    public javax.swing.JTextField descripciontxt;
    public javax.swing.JTextField edadtxt;
    public javax.swing.JTextField fechatxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField nombretxt;
    public javax.swing.JTextField preciotxt;
    public javax.swing.JTextField serviciotxt;
    // End of variables declaration//GEN-END:variables
}
